--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlxiBoy1313/PlotChat
build-by-default: true
branches:
- main
projects:
  PlotChat:
    path: ""
    php: 8.0
    libs:
      - src: https://poggit.pmmp.io/ci/Vecnavium/FormsUI/FormsUI
        version: ^1.1.1
...
