############################
############################
####                                           ####
####   Chat addon for MyPlot   ####
####                                           ####
############################
############################

# settings, edit the settings of PlotChat
settings:
  cmd:
    enable: true
    command: "chat"
    desc: "PlotChat command"
    usage: "§cUse: /chat <message>"
    aliases: "pchat"
  see-chat:
    msg: "§8[§cAdmin§8] "
    # modes:
    # - "permission" => all peoples with a permisson
    # - "players" => all peoples in the player list
    # - "false" => disable this feauture
    mode: "permission"
    # if mode: permission
    mode-perms: "chat.see"
    # if mode: players
    mode-players:
      - "Player1"
      - "Player2"
  ui:
    enable: true
    # this is there when you do '/chat ui' that opens the UI.
    cmd: "ui"
  chat:
  # If this true, then only '/chat <on/off>' works. 
    enable: false
    cmd-on: "on"
    cmd-off: "off"
    usage: "§cUse: /chat <on, off>"

# messages, edit the message in the chat
message:
  prefix: "§6PlotChat §8» "
  cmd:
    no-plot: "§cYou are not standing inside a plot."
    no-world: "§cYou are not in a plot world."
    # formats:
    #  - %x% => see the plot position x
    #  - %z% => see the plot position z
    #  - %player% => see the player name
    #  - %msg% => see the player message
    chat-msg: "§6PlotChat §8| §7[§6%x%§8;§6%z%§7] §e%player% §8» §f%msg%"
    # Standart design: "PlotChat | [0;0] Player » Test"
    # Standart design Admin: "[Admin] PlotChat | [0;0] Player » Test"
    chat:
      cmd-on: "§aYou joint the PlotChat chat!"
      cmd-off: "§aYou leavt the PlotChat chat!"
  ui:
    title: "§6PlotChat"
    text: "§r\n§7Please send a PlotChat message."
    input: "§7Here..."