############################
############################
####                                           ####
####   Chat addon for MyPlot   ####
####                                           ####
############################
############################

# settings, edit the settings of PlotChat
settings:
  cmd:
    command: "chat"
    desc: "Write here in the plot chat"
    usage: "§cUse: /p chat <message, on-off, log, (ui)>"
  see-chat:
    msg: "§8[§cAdmin§8] "
    # modes:
    # - "permission" => all peoples with a permisson
    # - "players" => all peoples in the player list
    # - "false" => disable this feauture
    mode: "permission"
    mode-perms: "PlotChat.see"
    mode-players:
      - "Player1"
      - "Player2"
  ui:
    # if this true, then a UI can be opened.
    enable: false
    cmd: "ui"
  log:
    cmd: log
    # This is the permission to clear the log. If this is false, it will be displayed for everyone.
    admin-perms: "PlotChat.admin.log"
    admin-img: "textures/ui/trash"
    okay-img: "textures/ui/listcheck"
  chat:
    # this is command of enable or disable the chat
    cmd-on: "on"
    cmd-off: "off"
    # if this true, then you cannot use colors otherwise.
    color-chat: false
    color-chat-block:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 0
      - "a"
      - "b"
      - "c"
      - "d"
      - "e"
      - "o"
      - "r"
      - "f"
      - "l"
  world:
    # if this true, then you can only do /p chat in these worlds!
    enable: false
    worlds:
      - Plotworld1
      - Plotworld2

# messages, edit the message in the chat
message:
  prefix: "§6PlotChat §8» "
  cmd:
    no-plot: "§cYou are not standing inside a plot."
    no-world: "§cYou are not in a plot world."
    # formats:
    #  - %x% => see the plot position x
    #  - %z% => see the plot position z
    #  - %player% => see the player name
    #  - %msg% => see the player message
    chat-msg: "§6PlotChat §8| §7[§6%x%§8;§6%z%§7] §e%player% §8» §f%msg%"
    # Standart design: "PlotChat | [0;0] Player » Test"
    # Standart design Admin: "[Admin] PlotChat | [0;0] Player » Test"
    chat:
      cmd-on: "§aYou joint the PlotChat chat!"
      cmd-off: "§aYou leavt the PlotChat chat!"
  chat:
    title: "§6PlotChat"
    text: "§r\n§7Please send a PlotChat message."
    input: "§7Here..."
    not-message: "§cPlease write a message."
  log:
    # formats:
    #  - %x% => see the plot position x
    #  - %z% => see the plot position z
    #  - %user% => see the player name
    #  - %message% => see the message
    #  - %year% => see the year of the message
    #  - %month% => see the month of the message
    #  - %day% => see the day of the message
    #  - %hour% => see the hour of the message
    #  - %minute% => see the minute of the message
    title: "§6PlotChat §8| §7Log"
    text: "§r\n§aThis is the log from the plot §8[§6%x%§7;§6%z%§8]§a:"
    not-inlog: "§r\n§cThe log is currently empty."
    format: "§8[§b%year%:%month%:%day% | %hour%:%minute%§8] §c%user% §8| §a%message%"
    okay: "§7Okay"
    admin-delete: "§4Delete"
    admin-success: "§aThe log of plot §8[§6%x%§7;§6%z%§8] §ahas been deleted!"